### PR TITLE
Finish cloning apple old version homepage

### PR DESCRIPTION
**Pull request by NeerNim**
The online versions: https://rawcdn.githack.com/NeerNim/apple-clone/794bd25ab02f1c403cde71c93553d7d4abd8902c/index.html

The finished screenshot looks like this in my computer:

Screen Shot 2019-05-06 at 1 37 26 PM

### CODE REVIEW

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Looks great! 👍 . A couple of changes and you may 🚀 

Your code looks great, your README.md is fine and you have successfully added stickler. However, address the following concerns I have before I can give you the 👍  to merge to master.
- There is an issue with the hero text, on relatively smaller screens (13" and below). Below is what it looks like on original version vs your clone and same site. 
Screen Shot 2019-05-06 at 9 13 17 AM vs
Screen Shot 2019-05-06 at 9 12 57 AM
- And while you are addressing above issue should probably make the 'Watch the "Your Verse" film...' section smaller and a link (maybe add underline hover effect using `text-decoration: underline; ` on hover)
- The navbar also looks a bit wonky when it is shrunk in size, it does not behave like original but the search bar goes below and it looks like a table. (I, however, like the gradient effect you did! 👍 💯 )
- Also the search bar itself, the text is prompted before search icon when it should be after. You can use `text-indent` to fix. See image to understand the issue. 
Screen Shot 2019-05-06 at 9 12 38 AM
- the width of the apple icon and search bar sections of nav is a bit too much. It's a tad bit too wide.

Suggested improvement:
- You can add however effect to links to make this already awesome clone look even better 😄 .

**This is all I have to say. Project looks really good, address issues and submit another review and we can hopefully move on from their! Good Job 👍 . Your README is well done as well.**

***If you have any questions, let me know here or on slack and I will be glad to clarify with you.***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Hey, thanks for addressing some of the changes! 👍 😄 

- Noticed that the navbar now looks a bit more different than the original.
- Still, the issue of some of the Hero text missing

Screen Shot 2019-05-07 at 10 44 53 AM
Screen Shot 2019-05-07 at 10 46 37 AM

**I do notice it looks fine on your computer which means but l believe there is an underlying issue with CSS and structure that is causing the issue. What I do recommend however even if you are unable to solve the problem with the hero text please make the left end and right end sections of nav smaller, they are too wide (the icon area and search bar area, even in your screenshot is too wide.** 
**With all being said, I'm really happy with the way your project looks, at a minimum please fix navbar**
SEe original:
Screen Shot 2019-05-07 at 10 59 51 AM

***Please, if you need more guidance on how to fix these issues and what is causing them I am happy to dive in with you and figure it out. Message me on slack or other social media! We are so close 🚀***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

**Comment by NeerNim** [comment]
> # Hey, thanks for addressing some of the changes! 👍 😄
> * Noticed that the navbar now looks a bit more different than the original.
> * Still, the issue of some of the Hero text missing
> 
> Screen Shot 2019-05-07 at 10 44 53 AM
> Screen Shot 2019-05-07 at 10 46 37 AM
> 
> **I do notice it looks fine on your computer which means but l believe there is an underlying issue with CSS and structure that is causing the issue. What I do recommend however even if you are unable to solve the problem with the hero text please make the left end and right end sections of nav smaller, they are too wide (the icon area and search bar area, even in your screenshot is too wide.**
> **With all being said, I'm really happy with the way your project looks, at a minimum please fix navbar**
> SEe original:
> Screen Shot 2019-05-07 at 10 59 51 AM
> 
> _**Please, if you need more guidance on how to fix these issues and what is causing them I am happy to dive in with you and figure it out. Message me on slack or other social media! We are so close 🚀**_
> 
> **[--Maya](https://github.com/mcrd25)**
> [GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

Hi,
Thank you for reviewing my code. However, I have checked with all the resolutions between 768 and 1440px  in my responsive chrome tools and this is how it looks in the screenshot. If you are checking the online version then I updated the link and now it should look like in my screenshots.

Screen Shot 2019-05-07 at 6 31 15 PM

Screen Shot 2019-05-07 at 6 30 43 PM
Screen Shot 2019-05-07 at 6 30 36 PM

**Comment by mcrd25** [comment]
> > # Hey, thanks for addressing some of the changes! 👍 😄
> > 
> > * Noticed that the navbar now looks a bit more different than the original.
> > * Still, the issue of some of the Hero text missing
> > 
> > Screen Shot 2019-05-07 at 10 44 53 AM
> > Screen Shot 2019-05-07 at 10 46 37 AM
> > **I do notice it looks fine on your computer which means but l believe there is an underlying issue with CSS and structure that is causing the issue. What I do recommend however even if you are unable to solve the problem with the hero text please make the left end and right end sections of nav smaller, they are too wide (the icon area and search bar area, even in your screenshot is too wide.**
> > **With all being said, I'm really happy with the way your project looks, at a minimum please fix navbar**
> > SEe original:
> > Screen Shot 2019-05-07 at 10 59 51 AM
> > _**Please, if you need more guidance on how to fix these issues and what is causing them I am happy to dive in with you and figure it out. Message me on slack or other social media! We are so close 🚀**_
> > **[--Maya](https://github.com/mcrd25)**
> > [GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)
> 
> Hi,
> Thank you for reviewing my code. However, I have checked with all the resolutions between 768 and 1440px in my responsive chrome tools and this is how it looks in the screenshot. If you are checking the online version then I updated the link and now it should look like in my screenshots.
> 
> Screen Shot 2019-05-07 at 6 31 15 PM
> 
> Screen Shot 2019-05-07 at 6 30 43 PM
> Screen Shot 2019-05-07 at 6 30 36 PM

Hi, it does look better the nav however still looks like a table! If this is not the case for you, then you may merge to master however, if it is please address

**Review by mcrd25 — COMMENTED** [review]
Screen Shot 2019-05-10 at 6 35 28 AM
Hi, it does look better the nav however still looks like a table! If this is not the case for you, then you may merge to master however, if it is please address.


Everything looks great otherwise. Really well done 👍 💯 🏅

**Comment by NeerNim** [comment]
I checked it again but i cannot see the same result on my computer and even asked my coding partner to check it on his computer and it looks ok like here in the screenshot. I will merge it then thanks :)
Screen Shot 2019-05-10 at 1 23 05 PM

**Comment by mcrd25** [comment]
You have my approval then! Great job doing project, and thanks for your
patience!

**Pull request merged**
